# Generated by Django 3.2.8 on 2021-11-11 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_task_taskmember'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='column',
        ),
        migrations.RemoveField(
            model_name='task',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='task',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='task',
            name='deleted',
        ),
        migrations.RemoveField(
            model_name='task',
            name='description',
        ),
        migrations.RemoveField(
            model_name='task',
            name='hardest_level',
        ),
        migrations.RemoveField(
            model_name='task',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='task',
            name='updated_by',
        ),
    ]
